bids_root: /path/to/bids_root
bids_config: /path/to/bids_config.json
tabular: /path/to/tabular.csv
template: /path/to/template.nii.gz
mask: /path/to/mask.nii.gz

analysis:
  query: ""
  smoothing_fwhm: 5.0
  voxel_size: 6.0
  permutations: 100
  random_seed: 42
  multiple_comparisons: FDR

environment:
  testing: true

notes:
  no_raw_blsa_exported: true
  user_note: ""