# Example test config.yaml for NeuroVoxel
bids_root: /test/bids_root
bids_config: /test/bids_config.json
tabular: /test/tabular.csv
template: /test/template.nii.gz
mask: /test/mask.nii.gz

analysis:
  query: ""
  smoothing_fwhm: 5.0
  voxel_size: 6.0
  permutations: 100
  random_seed: 42
  multiple_comparisons: FDR

environment:
  testing: true

notes:
  no_raw_blsa_exported: true
  user_note: ""