# Example test config.yaml for NeuroVoxel
bids_root: /test/bids_root
bids_config: /test/bids_config.json
tabular: /test/tabular.csv
template: /test/template.nii.gz
mask: /test/mask.nii.gz

analysis:
  dependent: gm_ravensmap
  independent: diagnosis
  covariates:
    - age
    - sex
    - icv
  smoothing_fwhm: 8.0
  voxel_size: 2.0
  permutations: 500
  random_seed: 123
  multiple_comparisons: Bonferroni

environment:
  app_version: 1.2.3
  git_commit: 789abc456def
  libraries:
    streamlit: 1.32.0
    pandas: 2.3.0
    numpy: 1.27.0
    bids: 0.16.0

integrity:
  bids_root_hash: "abc123"
  tabular_hash: "def456"
  template_hash: "ghi789"
  mask_hash: "jkl012"

notes:
  no_raw_blsa_exported: true
  user_note: "Test run for reproducibility."
